---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=2.2.1.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml
  #- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - python hello.py

  # Run the role/playbook with ansible-playbook.
  #- ansible-playbook -i tests/inventory tests/test.yml --skip-tags update,copy_host_ssh_id

