---
sudo: required

services:
  - docker

before_install:
  # Fetch base image and build new container
  - sudo docker pull ubuntu:14.04
  - sudo docker build --rm=true --tag=ansiblepoc .

script:
  # Run container in detached state
  - sudo docker run -itd --privileged --name=ansiblecon --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ansiblepoc
  # Check syntax of ansible playbook
  - sudo docker exec -it ansiblepoc ansible-playbook /etc/ansible/roles/role_under_test/play/test.yml --syntax-check
  - sudo docker exec -it ansiblepoc ansible --version
  # Run ansible playbook
  - sudo docker exec -it ansiblepoc ansible-playbook /etc/ansible/roles/role_under_test/play/test.yml

